# Generated by Django 4.1.4 on 2023-01-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='service_use_counter',
            field=models.IntegerField(default=0, editable=False, help_text='Количество запросов'),
        ),
    ]
