# Generated by Django 4.1.4 on 2023-01-11 05:46

from django.db import migrations, models
import termos.models


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stations',
            field=models.CharField(max_length=100, verbose_name=termos.models.Station),
        ),
    ]
