# Generated by Django 4.1.4 on 2023-01-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0002_alter_post_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stations',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='termos.station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
