# Generated by Django 4.1.4 on 2023-01-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0003_alter_post_stations_alter_station_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stations',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), to='termos.station'),
        ),
    ]
